//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string ID { get; set; }
        public string Email { get; set; }
        public string Payable { get; set; }
        public string Paid { get; set; }
        public string Due { get; set; }
        public string AID { get; set; }
        public string Date { get; set; }
        public string Bed_No { get; set; }
        public string Problem { get; set; }
    }
}
