//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
        public string Password { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Account_Type { get; set; }
        public string Image { get; set; }
        public string Blood { get; set; }
    }
}
