//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pinfo
    {
        public string FirstName { get; set; }
        public int Id { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public System.DateTime DoB { get; set; }
        public string Address { get; set; }
        public string BloodGroup { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
